services:

  db:

    image: postgres:15-alpine

    container_name: jeb_postgres

    # .env лежит прямо тут же, в корне!

    env_file:

      - .env

    environment:

      POSTGRES_DB: ${POSTGRES_DB}

      POSTGRES_USER: ${POSTGRES_USER}

      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:

      - "5432:5432"

    volumes:

      - postgres_data:/var/lib/postgresql/data



  web:

    build: .

    container_name: jeb_django_web

    command: python manage.py runserver 0.0.0.0:8000

    ports:

      - "8000:8000"

    env_file:

      - .env

    # Мапим папку jeb_core в корень контейнера, чтобы изменения кода подхватывались на лету

    volumes:

      - ./jeb_core:/app

    depends_on:

      - db



volumes:

  postgres_data: