# Generated by Django 6.0.2 on 2026-04-17 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, unique=True, verbose_name='Название')),
                ('slug', models.CharField(max_length=75, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, unique=True)),
                ('slug', models.CharField(max_length=75, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='CpuList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, unique=True)),
                ('slug', models.CharField(max_length=75, unique=True, verbose_name='URL')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен')),
            ],
        ),
        migrations.CreateModel(
            name='GpuList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, unique=True)),
                ('slug', models.CharField(max_length=75, unique=True, verbose_name='URL')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен')),
            ],
        ),
        migrations.CreateModel(
            name='RamList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, unique=True)),
                ('slug', models.CharField(max_length=75, unique=True, verbose_name='URL')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Название')),
                ('slug', models.CharField(max_length=75, unique=True, verbose_name='URL')),
                ('specs', models.JSONField(default=dict, verbose_name='Характеристики')),
                ('description', models.JSONField(default=dict, verbose_name='Описание')),
                ('main_image', models.ImageField(upload_to='component/main/', verbose_name='Главное фото')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Обновлен')),
                ('quantity_in_stock', models.PositiveIntegerField(default=1, verbose_name='В наличии (шт)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='catalog.category', verbose_name='Категория')),
                ('component_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='catalog.componenttype', verbose_name='Тип комплектующего')),
            ],
            options={
                'verbose_name': 'Комплектующее',
                'verbose_name_plural': 'Комплектующие',
                'ordering': ['component_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ComponentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='component/extra/', verbose_name='Фото')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.component', verbose_name='Комплектующее')),
            ],
            options={
                'verbose_name': 'Фото комплектующего',
                'verbose_name_plural': 'Фото комплектующих',
            },
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Название')),
                ('slug', models.CharField(max_length=75, unique=True, verbose_name='URL')),
                ('pc_case', models.CharField(max_length=75, verbose_name='Корпус')),
                ('power_unit', models.CharField(max_length=75, verbose_name='Блок питания')),
                ('storage', models.CharField(max_length=75, verbose_name='Накопитель')),
                ('description', models.JSONField(default=dict, verbose_name='Описание')),
                ('main_image', models.ImageField(upload_to='customPC/main/', verbose_name='Главное фото')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Обновлен')),
                ('quantity_in_stock', models.PositiveIntegerField(default=1, verbose_name='В наличии (шт)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computers', to='catalog.category', verbose_name='Категория')),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computers', to='catalog.cpulist', verbose_name='Процессор')),
                ('gpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computers', to='catalog.gpulist', verbose_name='Видеокарта')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computers', to='catalog.ramlist', verbose_name='Оперативная память')),
            ],
            options={
                'verbose_name': 'Компьютер',
                'verbose_name_plural': 'Компьютеры',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='customPC/extra/', verbose_name='Фото')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.computer', verbose_name='Компьютер')),
            ],
            options={
                'verbose_name': 'Фото компьютера',
                'verbose_name_plural': 'Фото компьютеров',
            },
        ),
    ]
