# Generated by Django 6.0.2 on 2026-03-07 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomComputer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('slug', models.CharField(max_length=75, unique=True)),
                ('cpu', models.CharField(max_length=55)),
                ('gpu', models.CharField(max_length=125)),
                ('orm', models.CharField(max_length=75)),
                ('pc_case', models.CharField(max_length=75)),
                ('power_unit', models.CharField(max_length=75)),
                ('storage', models.CharField(max_length=75)),
                ('description', models.JSONField()),
                ('main_image', models.ImageField(upload_to='customPC/main/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('quantity_in_stock', models.PositiveIntegerField(default=1, verbose_name='В наличии (шт)')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Уникальный идентификатор', max_length=50, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Например: 🌐, 📱, 🤖', max_length=50, verbose_name='Иконка (emoji)')),
                ('description', models.TextField(blank=True, help_text='Коротко о услуге (для карточки на сайте)', verbose_name='Описание')),
                ('is_popular', models.BooleanField(default=False, help_text='Показывать в блоке "Популярные услуги"', verbose_name='Популярная')),
                ('is_active', models.BooleanField(default=True, help_text='Отображать на сайте', verbose_name='Активна')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='customPC/extra/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.customcomputer')),
            ],
        ),
        migrations.CreateModel(
            name='BuisnessAppeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('company_name', models.CharField(max_length=200, verbose_name='Название компании')),
                ('company_size', models.CharField(choices=[('small', 'Малый бизнес (1-10 человек)'), ('medium', 'Средний бизнес (11-50 человек)'), ('large', 'Крупный бизнес (50+ человек)')], max_length=50, verbose_name='Размер компании')),
                ('industry', models.CharField(max_length=100, verbose_name='Сфера деятельности')),
                ('project_description', models.TextField(verbose_name='Описание проекта')),
                ('budget_range', models.CharField(choices=[('under_100k', 'До 100 000 руб'), ('100k_500k', '100 000 - 500 000 руб'), ('500k_1m', '500 000 - 1 млн руб'), ('1m_plus', 'Более 1 млн руб')], max_length=50, verbose_name='Бюджет')),
                ('timeline', models.CharField(choices=[('urgent', 'Срочно (1-2 недели)'), ('fast', 'Быстро (1 месяц)'), ('normal', 'Обычно (2-3 месяца)'), ('flexible', 'Гибкие сроки')], max_length=50, verbose_name='Сроки')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('review', 'На рассмотрении'), ('contacted', 'Связались'), ('accepted', 'Принята'), ('rejected', 'Отклонена')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('service_type', models.ManyToManyField(blank=True, to='main.service')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='OrderChina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(help_text='Уникальный номер заказа/трека', max_length=100, unique=True, verbose_name='Трек-номер')),
                ('goods_description', models.TextField(help_text='Что именно везём? (Например: "Электроника: наушники 50шт")', verbose_name='Описание товара')),
                ('goods_category', models.CharField(blank=True, help_text='Например: электроника, одежда, запчасти', max_length=100, verbose_name='Категория товара')),
                ('total_weight_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общий вес (кг)')),
                ('total_volume_m3', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Объём (м³)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество мест')),
                ('supplier_name', models.CharField(help_text='Название компании/магазина в Китае', max_length=200, verbose_name='Поставщик')),
                ('supplier_contacts', models.TextField(blank=True, verbose_name='Контакты поставщика')),
                ('warehouse_from', models.CharField(default='Гуанчжоу', help_text='Город или адрес склада', max_length=200, verbose_name='Склад в Китае')),
                ('delivery_to', models.CharField(help_text='Город и адрес получателя', max_length=200, verbose_name='Адрес доставки в РФ')),
                ('delivery_method', models.CharField(choices=[('sea', 'Море (контейнер)'), ('air', 'Авиа'), ('rail', 'Ж/д'), ('express', 'Экспресс-доставка (DHL/FedEx)'), ('cargo', 'Сборный груз')], default='cargo', max_length=20, verbose_name='Способ доставки')),
                ('declared_value_usd', models.DecimalField(decimal_places=2, help_text='Для страховки и таможни', max_digits=12, verbose_name='Декларируемая стоимость ($)')),
                ('delivery_cost_rub', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Стоимость доставки (₽)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('pickup_date', models.DateField(blank=True, null=True, verbose_name='Плановая дата забора')),
                ('estimated_arrival', models.DateField(blank=True, null=True, verbose_name='Планируемая дата прибытия')),
                ('status', models.CharField(choices=[('new', 'Новая заявка'), ('processing', 'В обработке'), ('purchasing', 'Закупка товара'), ('storage', 'На складе в Китае'), ('in_transit', 'В пути'), ('customs', 'На таможне'), ('in_russia', 'В России'), ('delivered', 'Доставлен'), ('cancelled', 'Отменён')], default='new', max_length=20, verbose_name='Статус заказа')),
                ('payment_status', models.CharField(choices=[('not_paid', 'Не оплачен'), ('partial', 'Частично оплачен'), ('paid', 'Оплачен'), ('refund', 'Возврат')], default='not_paid', max_length=20, verbose_name='Статус оплаты')),
                ('notes', models.TextField(blank=True, help_text='Особые отметки, нюансы доставки', verbose_name='Примечания')),
                ('is_fragile', models.BooleanField(default=False, verbose_name='Хрупкий груз')),
                ('insurance', models.BooleanField(default=False, verbose_name='Нужна страховка')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='china_orders', to='main.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказ из Китая',
                'verbose_name_plural': 'Заказы из Китая',
                'indexes': [models.Index(fields=['tracking_number'], name='main_orderc_trackin_fc1421_idx'), models.Index(fields=['status'], name='main_orderc_status_c2ec49_idx'), models.Index(fields=['-created_at'], name='main_orderc_created_73a19c_idx')],
            },
        ),
    ]
